# The Docker image that will be used to build your app
image: golang:1.25
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  before_script:
    - go mod tidy
  script:
    - |
      cat <<EOF > metago.csv
      package,vcs,repo
      metago,git,gitlab.com/paste/metago
      jkr,git,gitlab.com/paste/jkr
      eyespy,git,gitlab.com/paste/eyespy
      i,git,gitlab.com/paste/i
      EOF
    - go run . build go.tahirmurata.com
